### ISSUE TITLE
Poor contrast with light wallpaper

### ISSUE THREAD

**Issue by mdh34** [elementary/greeter#108]
The greeter has poor contrast with a light wallpaper - maybe we can do what wingpanel does and change the text colour, or maybe #75 would fix this

![screenshot from 2018-05-14 19-33-15](https://user-images.githubusercontent.com/12615975/40016335-ea34da76-57ad-11e8-9364-d79f4ed86a85.png)

**Comment by SixFingeredAmish** [comment]
I wonder if the team wants to make the text black if the system senses a light background

**Comment by D0J0P** [comment]
Can confirm. In mine, the date and time don't look great because they're behind a light background. My name is in a darker spot of the background, so I'm not sure making only the date and time black while keeping my name white would be ideal. 
![img_20181018_095654016](https://user-images.githubusercontent.com/19495660/47160369-cd4fa180-d2bd-11e8-98e3-e68ed5a164d3.jpg)
