### ISSUE TITLE
Provide dbus interface to the panel

### ISSUE THREAD

**Issue by danrabbit** [elementary/greeter#132]
We need to provide the interface for getting background variance to the panel so that it can be transparent and/or light/dark where appropriate

**Comment by donadigo** [comment]
I think this would be resolved automatically now that we have a compositor in place that would draw the background and have the wingpanel gala plugin just loaded in compositor? This is how it's currently done in a normal session.

**Comment by torikulhabib** [comment]
in my opinion, should be in greeter mode, the wingpanel is positioned above the greeter.
because when the wingpanel appears the greeter is like being pressed down.

if not mistaken wingpanel ever experienced a bug, where all the maximized applications are under the wingpanel so that the maximum button and the lid are closed by wingpanel.

maybe if an exception is done in greeter, wingpanel is above the greeter maybe
Dark of wingpanel fixed.
just opinion

**Comment by danrabbit** [comment]
@donadigo the problem is that the compositor can't draw the background right now because Clutter can't have a transparent background

**Comment by danrabbit** [comment]
I'm going to drop this from the beta2 milestone because this is now an enhancement and no longer a regression

**Comment by danrabbit** [comment]
I'm going to close this since the new greeter design resolves this automatically
