### ISSUE TITLE
Wallpapers set via Fondo do not show up in lock screen

### ISSUE THREAD

**Issue by jlnr** [elementary/greeter#309]
When I manually import wallpapers or use a system wallpaper, I see the thumbnail in greeter.

If I use Fondo, or manually set a wallpaper that has been imported by Fondo, I only see the Juno default wallpaper in greeter.

**Comment by peteruithoven** [comment]
This would be a Fondo issue, because it would need to change another file.

Also this is referring to the behaivior of the currently released Greeter, we're working on a completely new Greeter which doesn't have a wallpaper on the background. 
See for example: https://www.reddit.com/r/elementaryos/comments/c68q3u
/call_for_testing_the_new_login_lock_screen/
Video: https://www.youtube.com/watch?v=CNzZRwNzrnY

So I'm closing this issue.

**Comment by jlnr** [comment]
@peteruithoven This is with the new greeter (daily). Since the wallpaper shows up in System Settings and can be selected there, it doesn't seem like Fondo stores the image in a super unusual place. I will investigate now to make sure which repository this issue belongs into.

**Comment by jlnr** [comment]
You were right, this was a permission issue with the downloaded wallpapers that should be fixed in Fondo.

**Comment by peteruithoven** [comment]
Thanks for the correction! It's all a bit confusing now more and more people are using the new Greeter.
