### ISSUE TITLE
The new greeter shows cards for disabled users

### ISSUE THREAD

**Issue by samermi1** [elementary/greeter#328]
I have a rocketchat user on my OS and it's disabled, but the new greeter shows this user as a card to log in to.

**Comment by raibtoffoletto** [comment]
Can confirm that my Libvirt user is appearing as well, although the account is marked as disabled in both my laptop and desktop.

**Comment by danrabbit** [comment]
So there's a couple reasons behind not binding enabled and visible states and I think we need to address those before reverting this change:

Specifically for libvirt qemu and other `nologin-shell` accounts, this appears to be a bug in accountsservice. We can probably find a workaround to check for this configuration that doesn't affect disabled users: https://askubuntu.com/questions/897026/why-do-i-have-a-libvirt-qemu-account-in-lock-switch-account-options-in-ubuntu/940069#940069

I believe that we use the disabled state (or maybe we wanted to use it?) for users that have timed out with Parental Controls/Digital Wellbeing. In this case, we need to show the cards so that:
a. Users don't just disappear without any feedback which looks like a critical bug
b. Administrators can override the disabled state from the greeter if they so desire

**Comment by raibtoffoletto** [comment]
What about adding a option "System account" in the drop-down menu Standard/Admin in switchboard? I don't mind seeing libvirt-qemu in there with my disabled guest account, and would "solve" the accountservice problem? Plus, sometimes is useful to create other logins to mess around (like testing some npm packages that I don't trust) but it is not necessarily to have in the greeter...

I agree about showing the cards for disabled accounts, it is a perfect normal behavior if you are using it with the parental control, the account shouldn't vanish, just prevent the log-in.

**Comment by doublehourglass** [comment]
> I agree about showing the cards for disabled accounts, it is a perfect normal behavior if you are using it with the parental control, the account shouldn't vanish, just prevent the log-in.

Maybe there could be a switch in greeter to disable showing disabled accounts? That wouldn't solve this issue, though.

**Comment by danrabbit** [comment]
Okay so after talking to upstream, Ubuntu is dropping their patch to AccountsService and so nologinshell users like libvirt qemu will no longer appear after we get that update. I would guess that a rocketchat user should fall under this as well as users created for running untrusted programs.

If we want to be able to create system users graphically, that would need to be an issue filed against [User Accounts Settings](https://github.com/elementary/switchboard-plug-useraccounts/issues/new)

**Comment by cassidyjames** [comment]
As a further note, I believe we _do_ still want to show normal human user accounts that have been disabled, because I think we'd like to use enabling/disabling the user account for Parental Control functionality. But system accounts should not show.

**Comment by danrabbit** [comment]
Sounds like we can close this issue as "Out of Scope" for Greeter then. Nothing more to do here :)
