### ISSUE TITLE
Numlock not turned on by default.

### ISSUE THREAD

**Issue by wedsonlopes** [elementary/greeter#403]
The numlock should be turned on by default or at least have an option for doing this on system settings.

**Comment by cassidyjames** [comment]
Numlock cannot be turned on by default because some hardware keyboards (especially on laptops) put the numlock keys on a layer above the standard alphabet keys, leading to extremely confusing situations where numbers are being typed instead of letters. elementary OS should remember what the previous state was, though, meaning once you turn it on once it should stay on and persist across reboots. Are you not seeing that behavior?

**Comment by davidmhewitt** [comment]
The other thing you can try is uncomment the `#activate-numlock=true` line in `/etc/lightdm/io.elementary.greeter.conf`

**Comment by wedsonlopes** [comment]
> The other thing you can try is uncomment the `#activate-numlock=true` line in `/etc/lightdm/io.elementary.greeter.conf`

I worked for me. Thanks!

**Comment by wedsonlopes** [comment]
> Numlock cannot be turned on by default because some hardware keyboards (especially on laptops) put the numlock keys on a layer above the standard alphabet keys, leading to extremely confusing situations where numbers are being typed instead of letters. elementary OS should remember what the previous state was, though, meaning once you turn it on once it should stay on and persist across reboots. Are you not seeing that behavior?

I understand the point! Makes sense. "elementary OS should remember what the previous state was, though, meaning once you turn it on once it should stay on and persist across reboots. Are you not seeing that behavior?" when the system reboots it turn out that the system not save the state of activation that I left.
