### ISSUE TITLE
How do I get back the way it was before?

### ISSUE THREAD

**Issue by jaaoelias** [elementary/greeter#474]
I didn't found here on github how do I get back the way it was before.
I'm new on Linux, sorry if this is trivial and I dont know

**Comment by davidmhewitt** [comment]
GitHub is a place for reporting bugs and requesting features. Please use the [elementary OS stackexchange](https://elementaryos.stackexchange.com/) for asking questions. You can also search on there for previously answered questions.

However, the "old design" of the greeter was intentionally replaced (and several issues were fixed by it then and since then), so it's not intended to be switched back by the user, hence why it's not easy or recommended.
