### ISSUE TITLE
No zoom function

### ISSUE THREAD

**Issue by cassidyjames** [elementary/greeter#540]
## Problem

Brought up in @techdev5521's edw talk. There's currently no equivalent to the zoom function in Gala which can be critical for users of impaired/low vision.

## Proposal

Implement the same zoom as in Gala in the greeter compositor, ideally with the same shortcuts and potentially a way to trigger it visually from the a11y indicator

## Prior Art

The macOS login screen supports the same zoom feature as in the session

**Comment by janxkoci** [comment]
This reminds me that I experience a race condition related to zoom and my Czech keyboard layout. Specifically, after some reboots I can zoom with `Super+1` (the key above letter `Q`) while other times the same key combo switches to 1st workspace. This is probably because in the Czech layout the key represents `+`, while holding Shift corresponds to `1`.

It's very edge-casey so I haven't reported it to Gala repo yet. Should I?
